config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart'
  get 'view_order' => 'cart#view_order'
  get 'checkout' => 'cart#checkout'
  post 'order_complete' => 'cart#order_complete'
  devise_for :users
  get 'categorical'=>'storefronts#items_by_category'
  get 'branding'=>'storefronts#items_by_brand'
  
  root 'storefronts#all_items'
  resources :categories
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        
        <ul class="nav navbar-nav">
          <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
             <ul class="dropdown-menu">
              <% @categories.each do |category| %>
                <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
              <% end %>
             </ul>
          </li>
          <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands <span class="caret"></span></a>
             <ul class="dropdown-menu">
              <% @brands.each do |brand| %>
                <li><%= link_to brand, branding_path(brand: brand) %></li>
              <% end %>
             </ul>
          </li>
        </ul>  

        <ul class="nav navbar-nav navbar-right">
          <% if can? :create, Product %>
          <li><%= link_to "Catalog", products_path %></li> 
          <% end %>
          <li><%= link_to "View Cart", view_order_path %></li>
          <% if user_signed_in? %>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toogle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello, <%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %></li>
            </ul>
          </li>
          <% else %>
           <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
        </div>
      </nav>
    <%= yield %>
    </div>
  </body>
</html>